# Generated by Django 4.0.6 on 2022-08-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('workid', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='apellido',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='fecha_creacion',
            new_name='date_open',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='descripcion',
            new_name='description',
        ),
    ]
